### ISSUE TITLE
Template centre frequency

### ISSUE THREAD

**Issue by loostrum** [AA-ALERT/dadafits#1]
Centre frequency (key `OBSFREQ`) should be `1400`.

**Comment by jiskattema** [comment]
Are the frequencies now correct? The documentation wants the 'center of frequency' for each channel, so we would still need to add 1/2 a channel offsets everywhere?

**Comment by loostrum** [comment]
I'm not sure how the frequencies for each channel are calculated. In any case, the highest frequency should be `OBSFREQ + .5 * BANDWIDTH - .5 * CHANNEL_BANDWIDTH`. or `1549.609375` (for 384 channels). I can check this further if I have a working fits file again.

**Comment by loostrum** [comment]
Ah I see this line now `freqs[i] = min_frequency + i * bandwidth;`
I believe that should indeed be offset by half a channel bandwidth. min_frequency is 1250, so it should have an additional ` + .5 * bandwidth`
