### ISSUE TITLE
PARSET documentation

### ISSUE THREAD

**Issue by jiskattema** [AA-ALERT/dadafits#11]
The PARSET is read from the PSRDADA ringbuffer and copied to the FITS header.
Can we add some info on the actual data:
* If i remember, it is compressed and then encoded XML or so. can we add decode instructions?
* is there a link we can point to for its description?

**Comment by loostrum** [comment]
I have added an explanation of the PARSET encoding. I cannot find a link to public documentation of the PARSET format itself, but I've added some info on the format to the README.
